server:
  port: 9094
  
spring:
  application:
    name: GROCERY-BILLING-SERVICE

  data:
    mongodb:
      uri: mongodb://localhost:27017/GroceryMongoDB

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone : http://localhost:8761/eureka/
  instance:
      hostname: localhost
