server:
  port: 9092
  
spring:
  application:
    name: GROCERY-CUSTOMER-SERVICE
  data:
    mongodb:
      uri: mongodb://localhost:27017/GroceryMongoDB

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone : http://localhost:8761/eureka/
  instance:
      hostname: localhost 
